// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("backend.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardOrder")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HotspotX")
                        .HasColumnType("REAL");

                    b.Property<double>("HotspotY")
                        .HasColumnType("REAL");

                    b.Property<string>("NarrativeText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentNote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SceneId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScienceFact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StoryId", "CardOrder")
                        .IsUnique();

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("backend.Models.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgeRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReadTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorldThemeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorldThemeId");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("backend.Models.StoryLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DotColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceStoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoryTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetStoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorldLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceStoryId");

                    b.HasIndex("TargetStoryId");

                    b.ToTable("StoryLinks");
                });

            modelBuilder.Entity("backend.Models.WorldTheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("WorldThemes");
                });

            modelBuilder.Entity("backend.Models.Card", b =>
                {
                    b.HasOne("backend.Models.Story", "Story")
                        .WithMany("Cards")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("backend.Models.Story", b =>
                {
                    b.HasOne("backend.Models.WorldTheme", "WorldTheme")
                        .WithMany("Stories")
                        .HasForeignKey("WorldThemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorldTheme");
                });

            modelBuilder.Entity("backend.Models.StoryLink", b =>
                {
                    b.HasOne("backend.Models.Story", "SourceStory")
                        .WithMany("Unlocks")
                        .HasForeignKey("SourceStoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Story", "TargetStory")
                        .WithMany("UnlockedBy")
                        .HasForeignKey("TargetStoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceStory");

                    b.Navigation("TargetStory");
                });

            modelBuilder.Entity("backend.Models.Story", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("UnlockedBy");

                    b.Navigation("Unlocks");
                });

            modelBuilder.Entity("backend.Models.WorldTheme", b =>
                {
                    b.Navigation("Stories");
                });
#pragma warning restore 612, 618
        }
    }
}
